site_name: Tobas
theme: readthedocs # cf. https://github.com/mkdocs/mkdocs/wiki/MkDocs-Themes
nav:
  - Introduction: index.md # Required
  - Getting Started:
      - Installation: installation.md
      - Boot Device Configuration: bootmedia_config.md
      - Setup Assistant: setup_assistant.md
      - Hardware Setup: hardware_setup.md
      - Flight Test: flight_test.md
      - Simulation: simulation.md
  - For Developers:
      - ROS API: ros_api.md
      - User Code (Python): user_code_py.md
      - User Code (C++): user_code_cpp.md
  - Additional Information:
      - What is UADF: what_is_uadf.md
      - Inertia Moment: inertia_moment.md
      - 3D Models: cad_models.md
      - System Architecture: system_architecture.md
      - Trouble Shooting: trouble_shooting.md
markdown_extensions:
  - admonition # Required for "note"
  - pymdownx.arithmatex: # Required for writing equations
      generic: true
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
